### ISSUE TITLE
Feature Request: Ignore List

### ISSUE THREAD

**Issue by Shizen** [DonnEssime/Ender-Salem#3]
With recent patches, it would be really nice, imo, if we could get a simple ignore list for objects to simply leave off the radar. Of course, more powerful features along the same lines could be proposed--custom association of symbol to objects, swappable object sets, etc. But I think a basic filter with a simple list of object to ignore would suffice in the short run and should be pretty easy? It'd be nice if it would save itself to a file between sessions, but even if you had to type it in fresh each session it'd still be quite useful.

**Comment by DonnEssime** [comment]
you can easily do it by changing your radar.xml file.
add show="false" to any object you do NOT wish to be shown.
The radar option tab will also allow you to temporarily show or not show groups in your radar file.

**Comment by Shizen** [comment]
Sadly, the granularity on the radar tab makes it useless.  Better if you could manually enter specific items to ignore or possibly select them from categorized drop downs, etc.  The radar.xml file, however, is brilliant, which solves the problem well enough for the nonce, imo.
